/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
    safelist: [
        "fill-white",
        "bg-red-300",
        "fill-red-950",
        "text-red-950",
        "bg-blue-300",
        "fill-blue-950",
        "text-blue-950",
        "bg-indigo-300",
        "fill-indigo-950",
        "text-indigo-950",
        "bg-purple-300",
        "fill-purple-950",
        "text-purple-950",
        "bg-pink-300",
        "fill-pink-950",
        "text-pink-950",
        "bg-emerald-300",
        "fill-emerald-950",
        "text-emerald-950",
        "bg-green-300",
        "fill-green-950",
        "text-green-950",
        "bg-teal-300",
        "fill-teal-950",
        "text-teal-950",
        "bg-orange-300",
        "fill-orange-950",
        "text-orange-950",
        "bg-slate-300",
        "fill-slate-950",
        "text-slate-950",
        "fill-slate-400",
    ],
    theme: {
        extend: {
            fontFamily: {
                glamour: ["Glamour", "serif"],
                apercu: ["ApercuPro", "sans-serif"],
            },
        },
    },
    plugins: [],
};
